"""Added vinculo_instagram field

Revision ID: b0b732fe758a
Revises: ba872004bf2e
Create Date: 2023-05-22 18:28:58.758065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b732fe758a'
down_revision = 'ba872004bf2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vincular_instagram', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_column('vincular_instagram')

    # ### end Alembic commands ###
